spring:
  application:
    name: Library
  profiles:
    active: dev

# === Логирование (общее для всех профилей) ===
logging:
  file:
    name: ./logs/library-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# === JWT (общий для всех профилей) ===
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# === Bucket4j (общий) ===
bucket4j:
  enabled: true