apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-library
  namespace: library-test

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: test-library

  template:
    metadata:
      labels:
        app: test-library

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: test-library
          image: registry.robotov.site/dev-library:faa7747
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:
            - secretRef:
                name: library-secrets

          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 60

          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi